export const ADD_TO_CART = "ADD_TO_CART";
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const PAGE_LOADING = "PAGE_LOADING";
